// @ts-nocheck
import {NICHES,TOPICS,MODES,POOLS,EVENTS,STATS} from './config.js?v=0.8.0';
import {Game,number,need,cap} from './engine.js?v=0.8.0';
import {roomScene,ROOM_ART} from './room-scene.js?v=0.8.0';
import {icon} from './icons.js?v=0.8.0';
import {RoomMotion,preserveRoom,roomResponse,rewardResponse} from './room-motion.js?v=0.8.0';
const roomMotion=new RoomMotion();
const game=Game.load();
let tab='room',panel='',step=0,last=performance.now(),lastSave=last,lastSig='',drawnFans=game.s.fans,drawnViews=game.s.views;
let lastSeen=game.latest?.history?.length||0;
const root=document.querySelector('#app');
const $=(q)=>document.querySelector(q);
const formatTime=n=>Math.max(0,n/1000).toFixed(1)+'秒';
const ROOM_NAMES=['起步出租屋','温馨拍摄间','专业创作间','顶流工作室'];
let feedback={text:'',kind:'notice'},feedbackTimer,focusOrigin;
function feedbackStrip(extra=''){return `<div class="feedback-strip ${extra}" role="status" aria-live="polite"><span class="feedback-icon">${icon('spark')}</span><span class="feedback-copy"></span></div>`;}
function updateFeedback(){document.querySelectorAll('.feedback-strip').forEach(el=>{const idle=!feedback.text;el.classList.toggle('feedback-idle',idle);el.classList.toggle('feedback-gain',feedback.kind==='gain');el.querySelector('.feedback-copy').textContent=feedback.text||(el.classList.contains('room-feedback')?'从这里，拍出你的'+(game.s.videos.some(v=>v.status==='done')?'下一条':'第一条')+'爆款':'每一条作品，都在积累你的影响力');el.querySelector('.feedback-icon').innerHTML=icon(feedback.kind==='gain'?'gift':'spark');el.setAttribute('aria-hidden',String(!!document.querySelector('.sheet')&&!el.closest('.sheet')));});}
function setFeedback(text,kind='notice'){if(feedback.kind==='gain'&&kind==='notice')return;clearTimeout(feedbackTimer);feedback={text,kind};updateFeedback();feedbackTimer=setTimeout(()=>{feedback={text:'',kind:'notice'};updateFeedback();},2200);}
function notify(message){setFeedback(message);}
function journeyBanner(){const task=game.journey,stage=game.journeyStep,ready=game.journeyReady;if(!task)return `<div class="journey-banner graduation">${icon('trophy')} 新人毕业！下一站，千粉博主</div>`;return `<div class="journey-banner ${ready?'journey-ready':''}"><div class="journey-icon">${icon(ready?'gift':'target')}</div><div class="journey-text"><small>创作进阶 ${stage+1} / 8</small><strong>${task.title}</strong><span>${task.hint}</span><div class="journey-track" aria-label="已完成 ${stage} 步">${Array.from({length:8},(_,i)=>`<i class="${i<stage?'complete':i===stage?'current':''}"></i>`).join('')}</div></div><button data-action="${ready?'claimJourney':'guide'}">${icon(ready?'gift':'arrow')}${ready?'领 '+task.reward:'去完成'}</button></div>`;}
function burst(message){setFeedback(message,'gain');}
function hud(){const s=game.s;return `<div class="game-hud"><div class="hud-heading"><div class="hud-brand"><span class="brand-star">${icon('play')}</span><span><b>顶流博主</b><small>记录生活，也被世界看见</small></span></div><div class="hud-top-right"><span class="hud-tag">${icon('calendar')}第 ${s.day} 天</span><span class="hud-tag">Lv.${s.level} 创作者</span></div></div><div class="resource-bar"><span class="resource">${icon('heart')}<span><b id="fan-counter">${number(drawnFans)}</b><small>粉丝</small></span></span><span class="resource">${icon('play')}<span><b id="view-counter">${number(drawnViews)}</b><small>播放</small></span></span><button class="resource wallet" data-action="shop" aria-label="查看资金与设备升级">${icon('coin')}<span><b>${number(s.wallet)}</b><small>资金 ＋</small></span></button></div>${tab==='room'?'':feedbackStrip()}</div>`;}
function mission(){const s=game.s;const v=game.latest;
 if(game.making)return `<div class="mission-card busy"><div class="mission-icon">${icon('film')}</div><div class="mission-copy"><strong>正在剪辑：${v.title}</strong><div class="progress"><i id="production-progress" style="width:${100*(1-v.remaining/v.total)}%"></i></div></div><span id="production-time">${formatTime(v.remaining)}</span></div>`;
 if(game.ready)return `<div class="mission-card ready"><div class="mission-icon">${icon('play')}</div><div class="mission-copy"><strong>视频制作完成！</strong><small>点击下方「发布视频」，让观众看到你的作品</small></div><span class="pulsing-arrow">↓</span></div>`;
 if(game.streaming)return `<div class="mission-card viral"><div class="mission-icon">${icon('chart')}</div><div class="mission-copy"><strong>正在推荐 · ${POOLS[Math.min(v.pool,4)].name}</strong><small>播放 <b id="live-views">${number(v.views)}</b>　新增粉丝 ${number(v.fans)}</small><div class="pools">${POOLS.map((p,i)=>`<i class="${i<v.pool?'complete':i===v.pool?'current':''}"></i>`).join('')}</div></div></div>`;
 if(v&&v.status==='done')return `<button class="mission-card done work-preview" data-action="tab" data-id="works" aria-label="查看最新作品：${v.title}"><img class="work-thumbnail" src="./assets/work-cover-v07.webp" alt="博主与猫咪的作品档案插画" width="768" height="512"><div class="mission-copy"><strong>最新作品：${v.title}</strong><small class="preview-metrics"><span>${icon('play')} ${number(v.views)}</span><span>${icon('heart')} ${number(v.likes)}</span><span>${icon('chat')} ${number(v.comments)}</span></small></div><span class="work-status">${icon('check')}<small>创作完成</small></span>${icon('chevron')}</button>`;
 return `<div class="mission-card first"><div class="mission-icon">${icon('spark')}</div><div class="mission-copy"><strong>从0粉丝开始，拍摄第一条视频！</strong><small>先点亮旧电脑，开启你的博主生涯</small></div><span class="pulsing-arrow">↓</span></div>`;}
function primary(){const s=game.s;
 if(game.ready)return `<button class="main-cta publish" data-action="publish">${icon('play')} 发布视频 · 选择冲榜策略 <span>→</span></button>`;
 if(game.making){const next=['cut','hook','cover'].find(k=>!game.making.edits?.[k]);return next? `<button class="main-cta editing-cta" data-action="edit" data-id="${next}">${icon('cut')} 点击剪辑加速 <span id="cta-time">${formatTime(game.making.remaining)}</span></button>`:`<button class="main-cta editing-cta" disabled>${icon('film')} 剪辑即将完成 · <span id="cta-time">${formatTime(game.making.remaining)}</span></button>`;}
 if(game.streaming)return `<button class="main-cta" data-action="skip">${icon('chart')} 查看作品成绩 <span>→</span></button>`;
 if(s.pendingEvent!==null)return `<button class="main-cta" data-action="event-open">${icon('mail')} 查看新的平台消息 <span>→</span></button>`;
 return s.videos.length?`<button class="main-cta" data-action="pc">${icon('pen')} 创作下一条作品 <span>→</span></button>`:`<button class="main-cta" data-action="quickstart">${icon('pen')} 拍摄第一条视频 <span>→</span></button>`;
}
function editTools(){const v=game.making;if(!v)return '';const actions=[['cut','cut','快剪','优化完播'],['hook','spark','加爆点','增强传播'],['cover','image','做封面','吸引点击']];return `<div class="room-actions edit-tools" aria-label="视频剪辑操作">${actions.map(([id,ico,label,hint])=>`<button data-action="edit" data-id="${id}" ${v.edits?.[id]?'disabled':''}>${icon(v.edits?.[id]?'check':ico)}<span><b>${v.edits?.[id]?'已完成':label}</b><small>${hint}</small></span></button>`).join('')}</div>`;}
function room(){const s=game.s;return `<main class="room-page"><div class="room-intro"><div class="room-title"><h2>${['我的小小出租屋','我的小小工作室','我的专业创作间','我的顶流工作室'][s.roomTier||0]}</h2><p>从一个小房间，开始分享我的热爱。</p></div>${journeyBanner()}</div><div class="scene-frame">${roomScene(game)}</div>${feedbackStrip('room-feedback')}${game.making?editTools():`<div class="room-actions illustrated-actions">${[['pc','laptop','电脑','创作','剪辑灵感，记录生活'],['phone','phone','手机','热点','捕捉热点，获取灵感'],['shop','equipment','设备','升级','提升效率，解锁更多']].map(([a,i,t,d,detail])=>`<button data-action="${a}"><img src="./assets/entry-${i}-v07.webp" alt="" aria-hidden="true" width="512" height="512"><span><b>${t}</b><small>${d}</small><em>${detail}</em></span>${icon('chevron')}</button>`).join('')}</div>`}${mission()}<div class="room-bottom">${primary()}</div></main>`;}

function growth(){const s=game.s;return `<section class="page-section"><div class="page-header"><small>CREATOR PROGRESSION</small><h2>${icon('growth')} 博主成长</h2><p>经验来自真实发布，每次升级可自由分配3个属性点。</p></div><div class="rounded-panel level-card"><div class="split"><strong>Lv.${s.level} · 新锐创作者</strong><span>${s.exp} / ${need(s.level)} EXP</span></div><div class="progress"><i style="width:${Math.min(100,s.exp/need(s.level)*100)}%"></i></div><p>可分配属性点 <b class="accent">${s.points}</b> · 当前单项上限 ${cap(s.fans)}</p></div><div class="stat-grid">${Object.entries(STATS).map(([k,name],i)=>`<div class="stat-card"><div class="stat-head"><span>${icon(['target','bulb','clock','clover','chat','coin'][i])} ${name}</span><b>${s.stats[k]}</b></div><div class="stat-progress"><i style="width:${s.stats[k]/cap(s.fans)*100}%"></i></div><small>${({sense:'增强热点洞察',creativity:'提升作品表现',speed:'缩短制作时间',luck:'增加特殊推荐几率',operation:'提高涨粉效率',business:'提高合作报价'})[k]}</small><button data-action="upstat" data-id="${k}" ${s.points<1||s.stats[k]>=cap(s.fans)?'disabled':''}>＋ 分配属性点</button></div>`).join('')}</div></section>`;}
function works(){const vs=[...game.s.videos].reverse();return `<section class="page-section"><div class="page-header"><small>CREATOR ANALYTICS</small><h2>${icon('film')} 作品档案馆</h2><p>看看每一条作品在哪个流量池停下，找到下条视频的突破点。</p></div>${vs.length?vs.map(v=>`<article class="rounded-panel work-card"><div class="split"><strong>#${v.id}　${v.title}</strong><span>DAY ${v.createdDay}</span></div><div class="work-metrics"><span>${icon('play')} ${number(v.views)} 播放</span><span>${icon('heart')} ${number(v.likes)} 赞</span><span>＋${number(v.fans)} 粉</span></div><div class="pools">${POOLS.map((p,i)=>`<i class="${i<v.pool?'complete':''}" title="${p.name}"></i>`).join('')}</div><p class="report">${v.report}</p>${v.metrics?`<details><summary>查看视频数据与推荐池流水</summary><div class="metric-bars">${[['opening','开头'],['completion','完播'],['engagement','互动'],['sharing','分享'],['match','受众']].map(([k,l])=>`<div><label>${l}</label><div class="progress"><i style="width:${v.metrics[k]}%"></i></div><b>${Math.round(v.metrics[k])}</b></div>`).join('')}</div>${v.history.map(h=>`<div class="split ledger"><span>${POOLS[h.index].name}</span><span>＋${number(h.delta)}播放 · ＋${number(h.fans)}粉丝</span></div>`).join('')}</details>`:''}</article>`).join(''):`<div class="rounded-panel empty-state">${icon('film')}<p>还没有作品，快去电脑前开启创作吧！</p><button data-action="pc">制作第一条视频 →</button></div>`}</section>`;}
function shop(){const s=game.s,tier=s.roomTier||0,price=[80,300,2500][tier],followers=[0,1000,100000][tier],published=s.videos.some(v=>v.status==='done');const reason=!published?'先发布第一条视频':s.fans<followers?'还差 '+number(followers-s.fans)+' 粉丝':s.wallet<price?'还差 '+number(price-s.wallet)+' 资金':'升级我的房间';return `<section class="page-section shop-page"><div class="page-header"><small>MAKE ROOM FOR YOUR DREAMS</small><h2>${icon('equipment')} 工作室升级</h2><p>看见下一步，把每一笔积蓄变成更好的创作环境。</p></div><div class="rounded-panel upgrade-preview"><div class="room-compare ${tier===3?'max-tier':''}"><figure><img src="./assets/${ROOM_ART[tier]}" alt="当前工作室布置" width="1448" height="1086"><figcaption><small>当前 · 阶段 ${tier+1}</small><strong>${ROOM_NAMES[tier]}</strong></figcaption></figure>${tier<3?`<span class="compare-arrow">${icon('arrow')}</span><figure class="next-room"><img src="./assets/${ROOM_ART[tier+1]}" alt="下一阶段工作室预览" width="1448" height="1086"><figcaption><small>下一步 · 阶段 ${tier+2}</small><strong>${ROOM_NAMES[tier+1]}</strong></figcaption></figure>`:''}</div><div class="room-benefits"><span>${icon('clock')} 制作耗时缩减 <b>${tier*5}%${tier<3?' → '+(tier+1)*5+'%':''}</b></span><span>${icon('spark')} 开头与完播品质 <b>+${tier}${tier<3?' → +'+(tier+1):''}</b></span><small>耗时最低1.2秒；已发布作品的数据不变。</small></div></div><div class="rounded-panel shop-offer">${tier<3?`<span class="offer-label">下一件小确幸</span><h3>${['补光灯、相机与灵感墙','双屏、麦克风与专业灯光','高级设备、柔光箱与金色奖牌'][tier]}</h3><div class="upgrade-requirements"><div class="${s.fans>=followers?'met':''}">${icon(s.fans>=followers?'check':'heart')}<span>所需粉丝 <b>${number(followers)}</b></span></div><div class="${s.wallet>=price?'met':''}">${icon('coin')}<span>升级资金 <b>${number(price)}</b></span></div></div><button class="main-cta" data-action="buyroom" ${!published||s.fans<followers||s.wallet<price?'disabled':''}>${icon(!published||s.fans<followers||s.wallet<price?'lock':'equipment')}${reason}</button><small>当前资金 ${number(s.wallet)} · 升级后可立即回房间查看</small>`:`<div class="max-studio">${icon('trophy')}<h3>你的顶流工作室，已经完成</h3><p>把热爱继续拍成作品。</p><button class="primary" data-action="tab" data-id="room">回到我的工作室 ${icon('arrow')}</button></div>`}</div></section>`;}
function modal(title,kicker,body,foot){return `<div class="shade" role="presentation"><div class="sheet" role="dialog" aria-modal="true" aria-label="${title}" tabindex="-1"><div class="sheet-grab"></div><div class="sheet-header"><div><small>${kicker}</small><h2>${title}</h2></div><button class="close" data-action="close" aria-label="关闭弹窗">×</button></div><div class="sheet-content">${body}</div>${feedbackStrip()}${foot||''}</div></div>`;}
function launchPanel(){const v=game.ready;return v?modal('选择发布策略','SHARE YOUR LITTLE STORY',`<div class="publish-preview"><img src="./assets/${ROOM_ART[game.s.roomTier||0]}" alt="本次创作环境"><div><small>作品已就绪</small><strong>${v.title}</strong><span>${v.niche} · ${MODES.find(m=>m.id===v.modeId).name}</span></div>${icon('check')}</div><p class="strategy-intro">选择这次最想收获的成长。</p><div class="strategy-grid"><button data-action="publishWith" data-id="reply"><span class="strategy-icon">${icon('chat')}</span><b>回复热评</b><small>新增粉丝 +35%</small><span>认真回复，留下更多观众</span></button><button data-action="publishWith" data-id="share"><span class="strategy-icon">${icon('share')}</span><b>分享到社群</b><small>推荐评分 +3</small><span>把作品带给更多新朋友</span></button></div>`,'<div class="sheet-footer"><button class="secondary full" data-action="close">再想想</button></div>'):'';}
function livePanel(){const v=game.latest;if(!v||!['recommending','done'].includes(v.status))return '';const done=v.status==='done';return modal(done?'本条作品成绩出炉！':'视频流量正在起飞',done?'A LITTLE STEP FORWARD':'YOUR STORY IS ON AIR',`<div class="result-cover"><img src="./assets/${ROOM_ART[game.s.roomTier||0]}" alt="作品创作环境"><div><span class="result-badge">${icon(done?'check':'play')}${done?'作品已归档':'推荐进行中'}</span><h3>${v.title}</h3><small>${v.strategy==='share'?'分享到社群 · 推荐评分 +3':'回复热评 · 新增粉丝 +35%'}</small></div></div><div class="live-board ${done?'is-settled':''}"><div class="live-stats"><div><small>${icon('play')}累计播放</small><b>${number(v.views)}</b></div><div><small>${icon('heart')}本条涨粉</small><b>+${number(v.fans)}</b></div><div><small>${icon('spark')}获赞</small><b>${number(v.likes)}</b></div></div><div class="recommendation-track" aria-label="真实推荐进度">${POOLS.map((pool,i)=>{const h=v.history.find(h=>h.index===i);return `<div class="pool-step ${h?'reached':''} ${!done&&i===v.pool?'active':''}"><span>${h?icon(h.passed?'check':'target'):`${i+1}`}</span><strong>${pool.name}</strong><small>${h?h.passed?'已突破':'本次止步':!done&&i===v.pool?'推荐中':'未进入'}</small></div>`;}).join('')}</div><p class="result-report">${done?v.report:'每突破一档推荐，播放与粉丝都会继续增长。'}</p></div>${done?`<div class="result-advice">${icon('bulb')}<span>去作品页看开头、完播与互动表现，再试一个新题材。</span></div>`:''}${game.journeyReady?`<button class="claim-in-live" data-action="claimJourney">${icon('gift')} 完成任务，领取 ${game.journey.reward} 资金</button>`:''}`,`<div class="sheet-footer"><button class="${done?'primary':'secondary'} full" data-action="${done?'closeLive':'skip'}">${done?'收下成绩 · 继续成长':'跳过动画，查看成绩'} ${icon('arrow')}</button></div>`);}
function createPanel(){const s=game.s,labels=['选择赛道','灵感选题','创作方式'],nicheIcons=['mask','gamepad','bowl','book'];let body='';
 if(step===0)body=`<div class="step-cards niche-steps">${NICHES.map((n,i)=>`<button data-action="selectNiche" data-id="${n}" class="select-card ${n===s.selectedNiche?'on':''}"><span class="choice-icon">${icon(nicheIcons[i])}</span><strong>${n}</strong><small>${['高传播的有趣生活','游戏高光与玩家共鸣','探店、料理与美味','干货输出、知识分享'][i]}</small></button>`).join('')}</div>`;
 if(step===1)body=`<div class="topic-steps">${game.topics.map(t=>`<button data-action="selectTopic" data-id="${t.id}" class="topic-choice ${t.id===s.selectedTopic?'on':''}"><div><strong>${game.hotspots.includes(t.id)?'<em>热搜</em>':''}${t.title}</strong><small>${icon(t.duration?'flame':'leaf')} ${t.duration?'热门趋势':'常青选题'}　竞争 ${'★'.repeat(t.competition)}</small></div><span>热度 ${t.heat}</span></button>`).join('')}</div>`;
 if(step===2)body=`<div class="mode-steps">${MODES.map((m,i)=>`<button data-action="selectMode" data-id="${m.id}" class="mode-choice ${m.id===s.selectedMode?'on':''}"><span class="choice-icon">${icon(['image','mask','film','book','heart'][i])}</span><div><strong>${m.name}</strong><small>${m.desc}</small></div><b>${Math.max(1.2,m.seconds/(1+.11*(s.stats.speed-1))*(1-.05*(s.roomTier||0))).toFixed(0)}秒</b></button>`).join('')}</div>`;
 const foot=`<div class="sheet-footer"><div class="step-dots">${labels.map((l,i)=>`<i class="${i===step?'on':''}"></i>`).join('')}</div><div class="sheet-buttons">${step>0?'<button class="secondary" data-action="back">← 上一步</button>':''}<button class="primary" data-action="${step===2?'start':'next'}" ${step===2&&!game.canStart?'disabled':''}>${step===2?game.s.wallet<game.mode.cost?'余额不足，换免费方式':icon('film')+' 开始制作':'下一步 →'}</button></div><small>${step===2?`预算 ${number(game.mode.cost)} · 预计 ${formatTime(game.seconds*1000)} · 当前余额 ${number(s.wallet)}`:labels[step]+'　'+(step+1)+'/3'}</small></div>`;
 return modal('创作者工作台','MAKE SOMETHING YOU LOVE',`<div class="flow-tabs">${labels.map((l,i)=>`<span class="${i===step?'active':''}">${i+1}. ${l}</span>`).join('')}</div>${body}`,foot);}
function phonePanel(){const ev=game.s.pendingEvent;const body=`<div class="phone-frame"><div class="phone-notch"></div><div class="phone-title">${icon('phone')} Creator Feed <small>今日 DAY ${game.s.day}</small></div><h3>${icon('flame')} 今天的热点</h3>${game.hotspots.map((id,i)=>{const t=TOPICS.find(x=>x.id===id);return `<button class="feed-item" data-action="hotpick" data-id="${id}"><b>0${i+1}</b><div><strong>${t.title}</strong><small>${t.niche} · 热度 ${t.heat}</small></div><span>↗</span></button>`;}).join('')}<h3>${icon('chat')} 平台消息</h3><button class="feed-item" data-action="${ev!==null?'event-open':'close'}"><b>${icon('mail')}</b><div><strong>${ev!==null?EVENTS[ev].title:'暂时还没有新消息'}</strong><small>${ev!==null?'点击处理随机事件':'继续发视频，会有新故事发生'}</small></div><span>${icon(ev!==null?'mail':'check')}</span></button></div>`;
 return modal('随身手机','PHONE · 热点与消息',body,'<div class="sheet-footer"><button class="secondary full" data-action="close">返回房间</button></div>');}
function eventPanel(){const e=EVENTS[game.s.pendingEvent];if(!e)return '';return modal(e.title,'A NEW LITTLE STORY',`<p class="event-description">${e.desc}</p><div class="event-buttons">${e.choices.map((c,i)=>`<button data-action="chooseEvent" data-id="${i}">${c[0]} <span>→</span></button>`).join('')}</div>`);}
function popups(){return panel==='live'?livePanel():panel==='launch'?launchPanel():game.s.pendingEvent!==null?eventPanel():panel==='create'?createPanel():panel==='phone'?phonePanel():'';}
function bottomNav(){return `<nav class="game-nav" aria-label="主菜单">${[['room','home','房间'],['growth','growth','成长'],['works','film','作品'],['shop','equipment','设备']].map(([id,ico,title])=>`<button class="${tab===id?'active':''}" data-action="tab" data-id="${id}" ${tab===id?'aria-current="page"':''}>${icon(ico)}<small>${title}</small></button>`).join('')}</nav>`;}
function key(){const s=game.s,v=game.latest;return [tab,panel,step,s.day,s.level,s.exp,s.points,s.fans,s.wallet,s.views,s.reputation,s.roomTier,s.selectedNiche,s.selectedTopic,s.selectedMode,s.pendingEvent,s.videos.length,s.guideStep||0,v?.status,v?.pool,v?.history?.length].join('|');}
function focusMatch(source,scope=root){if(!source)return null;const a=CSS.escape(source.action),id=source.id===undefined?'':`[data-id="${CSS.escape(source.id)}"]`;return scope.querySelector(`[data-action="${a}"]${id}`);}
function render(){const oldRoom=$('.room-art');const y=window.scrollY,oldDialog=$('.sheet'),scroll=$('.sheet-content')?.scrollTop||0,active=document.activeElement?.closest('[data-action]'),source=active?{action:active.dataset.action,id:active.dataset.id}:null;root.innerHTML=hud()+(tab==='room'?room():tab==='growth'?growth():tab==='works'?works():shop())+bottomNav()+popups();preserveRoom(oldRoom,$('.room-art'));const dialog=$('.sheet');roomMotion.connect($('.room-art'));document.body.classList.toggle('modal-open',!!dialog);if(dialog){if(oldDialog&&source?.action.startsWith('select'))$('.sheet-content').scrollTop=scroll;(oldDialog&&focusMatch(source,dialog)||dialog.querySelector('.close')||dialog).focus({preventScroll:true});}else{if(oldDialog)focusMatch(focusOrigin)?.focus({preventScroll:true});else focusMatch(source)?.focus({preventScroll:true});window.scrollTo(0,y);}updateFeedback();lastSig=key();}
function showCreate(){tab='room';if(game.ready){publish();return;}if(game.making){notify('正在制作，点击房间里的剪辑操作加速');return;}if(game.streaming){panel='live';render();return;}if(game.s.pendingEvent!==null){notify('先处理手机消息');return;}if(!game.s.videos.length){quickstart();return;}panel='create';step=0;render();}
function publish(){if(game.ready){panel='launch';tab='room';}}
function publishWith(strategy){if(game.publishReady(strategy)){panel='live';tab='room';notify(strategy==='share'?'分享完成！争取冲上更大的流量池':'回复评论！争取把观众留成粉丝');}}
function quickstart(){if(game.s.videos.length){showCreate();return;}game.chooseNiche('搞笑');game.chooseTopic('T001');game.chooseMode('casual');if(game.start()){panel='';tab='room';notify('第一条已经开拍！点击快剪按钮可提前完成');}else notify('当前还有待处理的视频或消息');}
function goGuide(){if(game.ready){publish();return;}if(game.streaming){panel='live';return;}if(game.making){notify('正在剪辑，点击房间下方的三个剪辑操作！');return;}switch(game.journeyStep){case 2:tab='growth';panel='';break;case 3:tab='room';panel='phone';break;case 6:tab='shop';panel='';break;default:if(!game.s.videos.length)quickstart();else showCreate();}}

function click(action,id){switch(action){case 'tab':tab=id;panel='';break;case 'pc':showCreate();break;case 'quickstart':quickstart();break;case 'guide':goGuide();break;case 'claimJourney':{const task=game.journey;if(game.claimJourney()){burst('任务完成 · +'+task.reward+' 资金');notify('新手任务完成！下个目标已解锁');}break;}case 'publishWith':publishWith(id);break;case 'closeLive':panel='';notify('下一条会更好！');break;case 'focus-pc':notify('点击剪辑操作加速制作');break;case 'edit':if(game.editVideo(id))notify(game.ready?'剪辑完成！马上发布视频':'剪辑优化成功，制作时间缩短！');break;case 'phone':panel='phone';tab='room';break;case 'shop':panel='';tab='shop';break;case 'event-open':panel='event';break;case 'chooseEvent':if(game.chooseEvent(Number(id))){panel='';notify('已处理平台消息');}break;case 'close':panel='';break;case 'selectNiche':game.chooseNiche(id);break;case 'selectTopic':game.chooseTopic(id);break;case 'selectMode':game.chooseMode(id);break;case 'next':step=Math.min(2,step+1);break;case 'back':step=Math.max(0,step-1);break;case 'start':if(game.start()){panel='';tab='room';notify('开工啦！正在剪辑第一条视频');}else notify('请先确认制作资金和任务状态');break;case 'publish':publish();break;case 'skip':game.skip();panel='live';notify('已快速结算，看看这条视频的成绩吧！');break;case 'hotpick':{if(game.chooseHotTopic(id)){step=1;panel='create';notify('已锁定热搜，发布这条视频即可推进任务');}}break;case 'upstat':if(game.upgrade(id))notify('属性升级成功！');break;case 'buyroom':if(game.roomUpgrade()){tab='room';burst('工作室升级 · '+ROOM_NAMES[game.s.roomTier]);}else notify('需要更多粉丝或资金才能升级');break;}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;if(!$('.sheet'))focusOrigin={action:el.dataset.action,id:el.dataset.id};const before={wallet:game.s.wallet,edits:JSON.stringify(game.making?.edits),making:!!game.making};click(el.dataset.action,el.dataset.id);render();if(el.dataset.action==='claimJourney'&&game.s.wallet>before.wallet)rewardResponse();if(el.dataset.action==='edit'&&before.edits!==JSON.stringify(game.making?.edits))roomResponse('edit');else if(!before.making&&game.making)roomResponse('start');});
document.addEventListener('keydown',e=>{const dialog=$('.sheet');if(!dialog)return;if(e.key==='Escape'&&game.s.pendingEvent===null){e.preventDefault();panel='';render();return;}if(e.key==='Tab'){const nodes=[...dialog.querySelectorAll('button:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
function initLaya(){const L=window.Laya;if(!L)return;Promise.resolve(L.init(750,1334)).then(()=>{roomMotion.setRuntime(L);L.stage.scaleMode='showall';L.stage.screenMode='vertical';L.stage.bgColor='#f7f2e8';L.stage.mouseEnabled=false;L.stage.renderingEnabled=false;L.stage.on(L.Event.VISIBILITY_CHANGE,()=>{L.stage.renderingEnabled=false;});document.querySelectorAll('body canvas, #layaContainer').forEach(el=>{el.setAttribute('aria-hidden','true');el.style.pointerEvents='none';el.style.display='none';});}).catch(e=>console.warn('Laya engine initialization',e));}
initLaya();render();
setInterval(()=>{const t=performance.now(),delta=Math.max(0,Math.min(1600,t-last));last=t;game.advance(delta);if(game.latest?.history?.length>lastSeen){lastSeen=game.latest.history.length;{const h=game.latest.history.at(-1);burst('作品收获 +'+number(h.delta)+' 播放 · +'+number(h.fans)+' 粉丝');notify(h.passed?'突破推荐流量池！':'本条视频流量结算完成');}}if(key()!==lastSig)render();drawnFans+=Math.ceil((game.s.fans-drawnFans)*.2);drawnViews+=Math.ceil((game.s.views-drawnViews)*.2);const f=$('#fan-counter'),v=$('#view-counter'),lv=$('#live-views'),wt=$('#production-time'),bt=$('#cta-time'),pg=$('#production-progress');if(f)f.textContent=number(drawnFans);if(v)v.textContent=number(drawnViews);if(lv&&game.latest)lv.textContent=number(game.latest.views);if(game.making){if(wt)wt.textContent=formatTime(game.making.remaining);if(bt)bt.textContent=formatTime(game.making.remaining);if(pg)pg.style.width=(100*(1-game.making.remaining/game.making.total))+'%';}if(t-lastSave>4000){game.save();lastSave=t;}},100);
window.addEventListener('pagehide',()=>game.save());document.addEventListener('visibilitychange',()=>{if(document.hidden)game.save();});

