// @ts-nocheck
import {NICHES,TOPICS,MODES,POOLS,EVENTS,STATS} from './config.js';
import {Game,number,need,cap} from './engine.js';
const game=Game.load();let tab='studio',paintedViews=game.s.views,paintedFans=game.s.fans,last=performance.now(),lastSave=performance.now(),lastSig='';
const root=document.querySelector('#app');const $=s=>document.querySelector(s);
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800);}
function header(){const s=game.s;return `<header><div class="brand"><span class="logo">✦</span><b>顶流博主<span class="pink">模拟器</span></b></div><div><span class="chip">DAY ${s.day}</span><span class="chip">Lv.${s.level}</span></div></header><div class="hero"><small>YOUR CREATOR JOURNEY</small><div class="big"><span id="heroFans">${number(paintedFans)}</span> <label>粉丝</label></div><div class="heroFooter"><span>累计有效播放 <b id="heroViews">${number(paintedViews)}</b></span><span>百万粉进度 <b>${(s.fans/1000000*100).toFixed(2)}%</b></span></div></div><div class="summary"><div><small>💰 创作资金</small><b>${number(s.wallet)}</b></div><div><small>🎬 发布作品</small><b>${s.videos.filter(x=>x.status!=='producing').length}</b></div><div><small>💜 账号口碑</small><b>${s.reputation}/100</b></div></div>`;}
function workCurrent(){const v=game.making||game.streaming||game.latest;if(!v)return '<div class="box empty">🎥<br>你还没有发布作品<br><small>从几百播放开始，成长为现象级顶流</small></div>';
let content;if(v.status==='producing'){content=`<div class="big noMargin" id="seconds">${(v.remaining/1000).toFixed(1)} 秒</div><small>视频制作进行中</small><div class="track"><i id="workBar" style="width:${100*(1-v.remaining/v.total)}%"></i></div>`;}else{content=`<div class="big noMargin" id="liveViews">${number(v.views)}</div><small>累计播放 · +${number(v.fans)} 粉丝</small><div class="steps">${POOLS.map((p,i)=>`<i class="${i<v.pool?'done':i===v.pool?'active':''}" title="${p.name}"></i>`).join('')}</div><small>当前进度 · ${POOLS[Math.min(v.pool,4)].name}</small>${v.status==='recommending'?'<button class="minor wide" data-action="skip">跳过动效，立即查看结算 →</button>':`<p class="feedback">${v.report}</p>`}`;}
return `<div class="box"><div class="row"><b>📈 流量监测中心</b><small>#${v.id} · ${v.status==='producing'?'制作中':v.status==='recommending'?'正在推荐':'结算完成'}</small></div><p class="muted">${v.title}</p>${content}</div>`;}
function studio(){const s=game.s;return `<section>${workCurrent()}</section><section><div class="row"><h3>🎯 选择创作赛道</h3><small>四大起始赛道</small></div><div class="pills">${NICHES.map((x,i)=>`<button data-action="niche" data-id="${x}" class="${s.selectedNiche===x?'selected':''}">${['🎭','🎮','🍜','📚'][i]} ${x}</button>`).join('')}</div></section><section><div class="row"><h3>🔥 选择视频选题</h3><small>今日 DAY ${s.day}</small></div><div class="topics">${game.topics.map(t=>`<button data-action="topic" data-id="${t.id}" class="topic ${s.selectedTopic===t.id?'selected':''}"><div><b>${game.hotspots.includes(t.id)?'<span class="tag">🔥 热榜</span>':''}${t.title}</b><small>${t.duration?'短期热点':'长期常青'} · 竞争 ${'★'.repeat(t.competition)}${s.stats.sense>=10?' · 趋势 '+(t.heat>=75?'↑':'→'):''}</small></div><label>热度 ${t.heat}</label></button>`).join('')}</div></section><section><div class="row"><h3>🎥 选择制作方式</h3><small>速度属性可缩短时间</small></div><div class="modes">${MODES.map(m=>`<button data-action="mode" data-id="${m.id}" class="${s.selectedMode===m.id?'selected':''}"><b>${m.name}</b><small>${m.desc}</small></button>`).join('')}</div><button class="primary" data-action="start" ${game.canStart?'':'disabled'}>${game.making?'⏳ 视频制作中':game.streaming?'📈 推荐结算中':s.pendingEvent!==null?'📨 先处理事件':s.wallet<game.mode.cost?'资金不足 · 选免费方式':'🎬 开始制作新视频'}</button><p class="hint">永久免费随手拍 · 发布时锁定品质快照</p></section>`;}
function growth(){const s=game.s,levelUp=need(s.level),d={sense:'提供热点情报与选题契合，10级显示趋势',creativity:'增加开头、完播、互动和分享表现',speed:'降低制作秒数，不低于8秒',luck:'特殊机会基础概率 '+((.01+.0007*(s.stats.luck-1))*100).toFixed(2)+'%',operation:'每级提升约1.2%的转粉效率',business:'提升商业能力，后续商单系统接入'};return `<section><div class="row"><h3>✨ 博主成长中心</h3><small>可分配点数 <em>${s.points}</em></small></div><div class="box"><div class="row"><b>Lv.${s.level} 创作者</b><small>EXP ${s.exp}/${levelUp}</small></div><div class="track"><i style="width:${100*s.exp/levelUp}%"></i></div><small>每升1级获得3点 · 当前属性上限Lv.${cap(s.fans)}</small></div><div class="stats">${Object.entries(STATS).map(([id,name])=>`<div class="stat"><div class="row"><b>${name}</b><strong>${s.stats[id]}</strong></div><p>${d[id]}</p><button data-action="upgrade" data-id="${id}" ${s.points===0||s.stats[id]>=cap(s.fans)?'disabled':''}>＋ 升级属性</button></div>`).join('')}</div></section>`;}
function works(){const vs=[...game.s.videos].reverse();return `<section><div class="row"><h3>🗂 我的作品与复盘</h3><small>${vs.length} 条</small></div>${vs.length?vs.map(v=>`<div class="box work"><div class="row"><b>${v.title}</b><small>DAY ${v.createdDay}</small></div><div class="workNums"><span>▶ ${number(v.views)}</span><span>♡ ${number(v.likes)}</span><span>涨粉 +${number(v.fans)}</span></div><p class="feedback">${v.report}</p>${v.metrics?Object.entries(v.metrics).filter(x=>x[0]!=='score'&&x[0]!=='originality').map(([k,n])=>`<div class="meter"><small>${({opening:'开头',completion:'完播',engagement:'互动',sharing:'分享',match:'匹配'})[k]}</small><div class="track"><i style="width:${Math.max(0,Math.min(100,n))}%"></i></div><small>${Math.round(n)}</small></div>`).join(''):''}<div class="log">${v.history.map(h=>`<div class="row"><small>${POOLS[h.index].name}${h.passed?' ↗':''}</small><small>+${number(h.delta)}播放 · +${number(h.fans)}粉</small></div>`).join('')}</div></div>`).join(''):'<div class="box empty">📹 发布一条视频后即可查看完整数据</div>'}</section>`;}
function event(){const i=game.s.pendingEvent;if(i===null)return '';const e=EVENTS[i];return `<div class="veil"><div class="dialog"><small class="pink">⚡ 随机事件</small><h2>${e.title}</h2><p>${e.desc}</p>${e.choices.map((c,i)=>`<button data-action="event" data-id="${i}">${c[0]} →</button>`).join('')}<small>每个事件只能选择一次</small></div></div>`;}
function render(){const scroll=window.scrollY,topicScroll=$('.topics')?.scrollTop||0;root.innerHTML=header()+(tab==='studio'?studio():tab==='growth'?growth():works())+`<nav>${[['studio','🎬','创作中心'],['growth','✨','人物成长'],['works','📊','作品复盘']].map(([id,ic,name])=>`<button data-action="tab" data-id="${id}" class="${tab===id?'selected':''}"><span>${ic}</span>${name}</button>`).join('')}</nav>`+event();if($('.topics'))$('.topics').scrollTop=topicScroll;window.scrollTo(0,scroll);lastSig=signature();}
function signature(){const v=game.latest;return [tab,game.s.day,game.s.level,game.s.points,game.s.wallet,game.s.reputation,game.s.videos.length,game.s.pendingEvent,v?.status,v?.pool,v?.history.length,game.s.selectedTopic,game.s.selectedMode].join('|');}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const a=el.dataset.action,id=el.dataset.id;switch(a){case 'tab':tab=id;break;case 'niche':game.chooseNiche(id);break;case 'topic':game.chooseTopic(id);break;case 'mode':game.chooseMode(id);break;case 'start':if(game.start())toast('开拍成功！视频正在制作');break;case 'skip':game.skip();toast('推荐结算完成');break;case 'upgrade':if(game.upgrade(id))toast('属性升级成功');break;case 'event':if(game.chooseEvent(+id))toast('事件已处理');break;case 'reset':if(confirm('确定清除进度并从0粉重新开始？'))game.reset();break;}render();});
function startLaya(){if(typeof window.Laya==='undefined'){console.warn('LayaAir 3.4 engine library not loaded');return;}const Laya=window.Laya;Promise.resolve(Laya.init(750,1334)).then(()=>{Laya.stage.scaleMode='showall';Laya.stage.screenMode='vertical';Laya.stage.bgColor='#080b19';const stars=new Laya.Sprite();Laya.stage.addChild(stars);for(let i=0;i<36;i++)stars.graphics.drawCircle((i*131+19)%750,(i*277+32)%1334,1+i%2,'#a49aff');stars.alpha=.24;}).catch(e=>console.warn('Laya initialization failed',e));}
startLaya();render();if(new URLSearchParams(location.search).get('qa')==='1')window.__qa={game,advance(ms){game.advance(ms);render();},snapshot(){return JSON.parse(JSON.stringify(game.s));},reset(seed){game.reset(seed);render();}};
setInterval(()=>{const now=performance.now(),delta=Math.max(0,Math.min(now-last,2000));last=now;game.advance(delta);paintedViews+=(Math.ceil((game.s.views-paintedViews)*.19));paintedFans+=(Math.ceil((game.s.fans-paintedFans)*.2));paintedViews=Math.min(paintedViews,game.s.views);paintedFans=Math.min(paintedFans,game.s.fans);
if(signature()!==lastSig)render();const hf=$('#heroFans'),hv=$('#heroViews');if(hf)hf.textContent=number(paintedFans);if(hv)hv.textContent=number(paintedViews);const v=game.latest;if(v?.status==='producing'){const sec=$('#seconds'),bar=$('#workBar');if(sec)sec.textContent=(v.remaining/1000).toFixed(1)+' 秒';if(bar)bar.style.width=(100*(1-v.remaining/v.total))+'%';}else if(v){const live=$('#liveViews');if(live)live.textContent=number(v.views);}if(now-lastSave>5000){game.save();lastSave=now;}},100);
window.addEventListener('pagehide',()=>game.save());document.addEventListener('visibilitychange',()=>{if(document.hidden)game.save();});
