import test from 'node:test';import assert from 'node:assert/strict';
import {Game,initial,need,cap} from '../js/engine.js';
import {TOPICS,MODES,POOLS,EVENTS} from '../js/config.js';
test('initial economy, content and pool counts',()=>{let s=initial(123);assert.equal(s.fans,0);assert.equal(s.wallet,100);assert.equal(s.stats.speed,2);assert.equal(TOPICS.length,30);assert.equal(MODES.length,5);assert.equal(POOLS.length,5);assert.equal(EVENTS.length,10);assert.equal(need(1),30);});
test('production is timed, cannot double start, and first pool starts at 200-800',()=>{const g=new Game(initial(123));assert.equal(g.start(),true);assert.equal(g.start(),false);g.advance(40000);assert.equal(g.latest.status,'ready');assert.equal(g.latest.views,0);assert.equal(g.publishReady(),true);g.advance(6000);assert.equal(g.latest.status,'done');assert.ok(g.latest.views>=200&&g.latest.views<=800);});
test('pool deltas are cumulative and never double book',()=>{const g=new Game(initial(123));g.start();g.advance(40000);g.publishReady();g.advance(6000);const before=g.s.views;const rows=g.latest.history;let running=0;for(const r of rows){running+=r.delta;assert.equal(r.target,running);}assert.equal(g.latest.views,before);g.skip();g.advance(6000);assert.equal(g.s.views,before);});
test('identical seed and actions yield identical quality and pool ledger',()=>{const sim=()=>{const g=new Game(initial(99));g.chooseMode('twist');g.start();g.advance(55000);g.publishReady();g.advance(6000);return{quality:g.latest.metrics,history:g.latest.history};};assert.deepEqual(sim(),sim());});
test('leveling adds points and upgraded speed shortens production',()=>{const g=new Game(initial(42));g.exp(31);assert.equal(g.s.points,3);const old=g.seconds;assert.equal(g.upgrade('speed'),true);assert.ok(g.seconds<old);g.s.points=0;assert.equal(g.upgrade('speed'),false);g.s.stats.speed=100;assert.equal(g.seconds,1.2);});
test('event choice is one-time and affects resources',()=>{const g=new Game(initial(55));g.s.pendingEvent=3;const rep=g.s.reputation;assert.equal(g.chooseEvent(0),true);assert.equal(g.s.reputation,rep+3);const fans=g.s.fans;assert.equal(g.chooseEvent(0),false);assert.equal(g.s.fans,fans);});
test('0 funds can still make a free video',()=>{const g=new Game(initial(44));g.s.wallet=0;g.chooseMode('premium');assert.equal(g.start(),false);g.chooseMode('casual');assert.equal(g.start(),true);g.advance(50000);assert.ok(g.s.fans>=0);});
test('past quality snapshot is not modified by future upgrades',()=>{const g=new Game(initial(31));g.start();g.advance(45000);g.publishReady();const prev=JSON.stringify(g.latest.metrics);g.exp(400);g.upgrade('creativity');assert.equal(JSON.stringify(g.latest.metrics),prev);});
test('offline time is capped and does not create negative values',()=>{const g=new Game(initial(17));g.start();g.advance(8*3600000,true);assert.ok(g.s.fans>=0&&g.s.views>=0);assert.ok(g.s.day<=321);assert.equal(cap(0),20);});

test('ready state blocks double production and event id 0',()=>{const g=new Game(initial(3));g.start();g.advance(40000);assert.equal(g.latest.status,'ready');assert.equal(g.start(),false);assert.equal(g.latest.views,0);g.publishReady();assert.equal(g.publishReady(),false);g.skip();g.s.pendingEvent=0;assert.equal(g.canStart,false);});
test('room upgrades affect future production but not previous snapshot',()=>{const g=new Game(initial(4));const base=g.seconds;assert.equal(g.roomUpgrade(),false);g.start();g.advance(40000);g.publishReady();g.skip();assert.equal(g.roomUpgrade(),true);assert.equal(g.s.roomTier,1);assert.ok(g.seconds<base);g.start();g.advance(40000);g.publishReady();const before=JSON.stringify(g.latest.metrics);g.s.wallet=9999;g.s.fans=1000;assert.equal(g.roomUpgrade(),true);assert.equal(JSON.stringify(g.latest.metrics),before);});

test('first video has short automatic production time',()=>{const g=new Game(initial(102));assert.ok(g.seconds<=3);g.start();assert.ok(g.making.remaining<=3000);g.advance(4000);assert.equal(g.ready.status,'ready');});
test('three editing actions shorten production and cannot double claim',()=>{const g=new Game(initial(103));g.chooseMode('premium');g.start();const before=g.making.remaining;assert.equal(g.editVideo('cut'),true);assert.ok(g.making.remaining<before);assert.equal(g.editVideo('cut'),false);assert.equal(g.editVideo('hook'),true);assert.equal(g.editVideo('cover'),true);g.advance(10000);assert.equal(g.latest.status,'ready');g.publishReady();assert.ok(g.latest.metrics.opening>0);assert.equal(g.editVideo('cut'),false);});

test('novice journey milestones are gated and each paid exactly once',()=>{const g=new Game(initial(900));assert.equal(g.journeyStep,0);assert.equal(g.claimJourney(),false);g.start();g.advance(5000);g.publishReady('reply');assert.equal(g.journeyReady,true);assert.equal(g.claimJourney(),true);assert.equal(g.journeyStep,1);assert.equal(g.claimJourney(),false);g.advance(7000);assert.ok(g.s.views>=200);assert.equal(g.claimJourney(),true);assert.equal(g.journeyStep,2);g.upgrade('sense');assert.equal(g.claimJourney(),true);assert.equal(g.journeyStep,3);});
test('the first video stays around hundreds of views, and later video strategies work',()=>{const sim=(strategy)=>{const g=new Game(initial(24));g.start();g.advance(5000);g.publishReady(strategy);g.advance(10000);return g;};const a=sim('reply'),b=sim('share');assert.equal(a.latest.strategy,'reply');assert.equal(b.latest.strategy,'share');assert.equal(a.latest.pool,1);assert.equal(b.latest.pool,1);assert.ok(a.latest.views>=300&&a.latest.views<=800);assert.ok(b.latest.views>=300&&b.latest.views<=800);assert.ok(a.latest.fans>=b.latest.fans);});
test('hotspot followup and no new-player accidental room purchase',()=>{const g=new Game(initial(123));assert.equal(g.roomUpgrade(),false);const id=g.hotspots[0];assert.equal(g.chooseHotTopic(id),true);g.start();assert.equal(g.s.trendShots,1);assert.equal(g.s.trendPicked,null);g.advance(5000);g.publishReady();g.skip();assert.equal(g.roomUpgrade(),true);});
test('Day 1 stays Day 1 before first filming and story can resume',()=>{const g=new Game(initial(22));g.advance(8*3600000,true);assert.equal(g.s.day,1);g.start();g.advance(90001);assert.ok(g.s.day>1);});

