import {createRequire} from 'node:module';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const modules=process.env.QA_MODULES||process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES;
const {chromium}=require(modules?modules+'/playwright':'playwright');
const url=process.env.QA_URL||'http://127.0.0.1:4173/';
const out=process.env.QA_OUT||'evidence/browser';mkdirSync(out,{recursive:true});
const b=await chromium.launch({headless:true});
const profiles=[{name:'target-512',width:512,height:768},{name:'mobile-360',width:360,height:740},{name:'mobile-390',width:390,height:844},{name:'mobile-430',width:430,height:932},{name:'desktop',width:1280,height:900}];
const report={version:'0.7.0',time:new Date().toISOString(),profiles:[],errors:[]};
const shots=[];const KEY='creator-simulator-save-v01';
async function shot(p,name){const path=out+'/'+name+'.png';await p.screenshot({path});shots.push({name,path,sha256:createHash('sha256').update(readFileSync(path)).digest('hex')});}
try{
for(const profile of profiles){
 const ctx=await b.newContext({viewport:{width:profile.width,height:profile.height},deviceScaleFactor:2,isMobile:profile.name.startsWith('mobile'),hasTouch:profile.name.startsWith('mobile')});
 const p=await ctx.newPage();const errors=[];
 p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});p.on('requestfailed',r=>errors.push(r.url()+' '+r.failure()?.errorText));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});
 const activate=async(selector)=>{const el=p.locator(selector).first();if(profile.name.startsWith('mobile'))await el.tap();else await el.click();};
 await p.goto(url);await p.locator('.room-illustration').evaluate(img=>img.decode());await p.evaluate(()=>document.fonts.load('24px CreatorBrush'));await p.evaluate(()=>document.fonts.ready);assert(await p.evaluate(()=>document.fonts.check('24px CreatorBrush')),'bundled brush font loads');await p.locator('.illustrated-actions img').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));assert.equal(await p.locator('.illustrated-actions img').count(),3);assert(await p.locator('.illustrated-actions img').evaluateAll(imgs=>imgs.every(img=>img.naturalWidth>=256&&img.naturalHeight>=256)),'painted entrance assets decode at useful resolution');
 const hero=await p.locator('.room-illustration').evaluate(img=>{const r=img.getBoundingClientRect();return {width:r.width,height:r.height,app:img.closest('#app').getBoundingClientRect().width};});assert(Math.abs(hero.width/hero.height-4/3)<.01,'room art keeps 4:3');assert(hero.width/hero.app>=(profile.name.startsWith('mobile')?.94:profile.name==='target-512'?.80:.85),'room is the visual centerpiece');
 assert.equal(await p.evaluate(()=>window.__qa),undefined,'production exposes no mutable debug bridge');
 assert(await p.locator('#fan-counter').innerText()==='0');
 const geometry=await p.evaluate(()=>{
  const nav=document.querySelector('.game-nav').getBoundingClientRect(),cta=document.querySelector('.room-bottom .main-cta').getBoundingClientRect();
  return {overflow:document.documentElement.scrollWidth>innerWidth,ctaBottom:cta.bottom,navTop:nav.top,ctaWidth:cta.width,viewport:innerHeight,hotspots:[...document.querySelectorAll('.room-hotspot')].map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,clickable:document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===e};})};
 });
 assert(!geometry.overflow,'no horizontal overflow');assert(geometry.ctaBottom<geometry.navTop,'CTA and navigation do not overlap');assert(geometry.ctaWidth>250);assert(geometry.hotspots.every(h=>h.clickable&&h.w>=44&&h.h>=40),'room controls visible and hit-testable');
 const missionBottom=await p.locator('.mission-card').evaluate(e=>e.getBoundingClientRect().bottom);console.log(JSON.stringify({profile:profile.name,geometry,missionBottom}));await shot(p,profile.name+'-home');assert(missionBottom<=await p.locator('.room-bottom .main-cta').evaluate(e=>e.getBoundingClientRect().top-10),'mission and action cards fully above CTA');
 await activate('.pc-hotspot');await p.locator('.edit-tools').waitFor();
 assert.equal(await p.locator('.scene-frame .edit-tools').count(),0,'editing never covers art');assert.equal(await p.locator('.edit-tools button').count(),3);assert(await p.locator('.edit-tools button').first().evaluate(e=>e.getBoundingClientRect().height)>=44);assert(await p.locator('.mission-card').evaluate(e=>e.getBoundingClientRect().bottom)<=await p.locator('.room-bottom .main-cta').evaluate(e=>e.getBoundingClientRect().top-10));await shot(p,profile.name+'-editing');await activate('[data-action="edit"][data-id="cut"]');
 await p.locator('.main-cta[data-action="publish"]').waitFor({timeout:10000});
 await activate('.main-cta[data-action="publish"]');await p.getByRole('dialog',{name:'选择发布策略'}).waitFor();await shot(p,profile.name+'-publish');
 await activate('[data-action="publishWith"][data-id="reply"]');await p.getByRole('dialog',{name:'本条作品成绩出炉！'}).waitFor({timeout:10000});
 assert.equal(await p.locator('.reward-float,#toast').count(),0,'no reward or toast overlays');assert.equal(await p.locator('.recommendation-track .reached').count(),1,'first video stops in its real pool');assert.equal(await p.locator('.recommendation-track .pool-step').first().locator('small').innerText(),'本次止步');assert(await p.locator('.sheet-footer button').evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&r.top>=0;}),'result action on screen');const resultValues=await p.locator('.live-stats b').allTextContents();const savedVideo=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).videos.at(-1),KEY);assert.equal(Number(resultValues[0].replaceAll(',','')),savedVideo.views);assert.equal(Number(resultValues[1].replace('+','').replaceAll(',','')),savedVideo.fans);await shot(p,profile.name+'-result');
 const views=await p.locator('.live-stats b').first().innerText();assert(Number(views.replaceAll(',',''))>=300&&Number(views.replaceAll(',',''))<=800);
 await activate('[data-action="closeLive"]');await p.locator('.shade').waitFor({state:'detached'});await p.locator('.work-thumbnail').evaluate(img=>img.decode());const actualMetrics=await p.locator('.preview-metrics>span').allTextContents();assert.deepEqual(actualMetrics.map(v=>Number(v.trim())),[savedVideo.views,savedVideo.likes,savedVideo.comments],'home work metrics use saved video');
 await activate('[data-action="claimJourney"]');await p.waitForTimeout(180);assert(await p.locator('.journey-text small').innerText()==='创作进阶 2 / 8');
 await activate('.phone-hotspot');await p.getByRole('dialog',{name:'随身手机'}).waitFor();assert.equal(await p.locator('.feed-item[data-action="hotpick"]').count(),4);await shot(p,profile.name+'-phone');await p.keyboard.press('Shift+Tab');assert.equal(await p.locator('[data-action="close"]').last().evaluate(e=>e===document.activeElement),true,'focus wraps inside dialog');await p.keyboard.press('Tab');assert.equal(await p.locator('.close').evaluate(e=>e===document.activeElement),true);await p.keyboard.press('Escape');assert.equal(await p.locator('.sheet').count(),0);assert.equal(await p.locator('.phone-hotspot').evaluate(e=>e===document.activeElement),true,'focus restored after dialog');
 await activate('.game-nav [data-id="growth"]');await p.locator('.stat-card').first().waitFor();assert.equal(await p.locator('.stat-card').count(),6);await shot(p,profile.name+'-growth');
 await activate('.game-nav [data-id="works"]');await p.locator('.work-card').waitFor();assert.equal(await p.locator('.work-card').count(),1);await shot(p,profile.name+'-works');
 await activate('.game-nav [data-id="shop"]');await p.locator('.upgrade-preview img').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));assert.equal(await p.locator('.upgrade-preview img').count(),2);assert.equal(await p.locator('.next-room img').getAttribute('src'),'./assets/room-cozy-v05.webp');assert((await p.locator('.room-benefits').innerText()).includes('0% → 5%'));const previewRatio=await p.locator('.upgrade-preview img').first().evaluate(img=>{const r=img.getBoundingClientRect();return r.width/r.height;});assert(Math.abs(previewRatio-4/3)<.01,'shop illustration preserves its natural size');await shot(p,profile.name+'-shop');
 await activate('[data-action="buyroom"]');await p.locator('.room-illustration[src*="cozy"]').waitFor();await p.locator('.room-illustration').evaluate(img=>img.decode());await shot(p,profile.name+'-upgraded');assert(await p.locator('.mission-card').evaluate(e=>e.getBoundingClientRect().bottom)<=await p.locator('.room-bottom .main-cta').evaluate(e=>e.getBoundingClientRect().top-10),'completed work remains fully above CTA');
 await activate('.main-cta[data-action="pc"]');await p.getByRole('dialog',{name:'创作者工作台'}).waitFor();await shot(p,profile.name+'-create-niche');await activate('[data-action="next"]');await shot(p,profile.name+'-create-topic');await activate('[data-action="next"]');await shot(p,profile.name+'-create-mode');assert(await p.locator('.sheet-footer').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight),'creation footer on screen');await activate('[data-action="start"]');await p.locator('.main-cta[data-action="publish"]').waitFor({timeout:10000});await activate('.main-cta[data-action="publish"]');await activate('[data-action="publishWith"][data-id="share"]');await p.getByRole('dialog',{name:'本条作品成绩出炉！'}).waitFor({timeout:10000});await activate('[data-action="closeLive"]');
 await p.getByRole('dialog').waitFor();assert.notEqual(await p.getByRole('dialog').getAttribute('aria-label'),'本条作品成绩出炉！');await p.keyboard.press('Escape');assert.equal(await p.locator('.sheet').count(),1,'pending platform event cannot be dismissed');await activate('[data-action="chooseEvent"][data-id="0"]');await p.reload();await p.locator('.room-illustration').evaluate(img=>img.decode());assert(await p.locator('#view-counter').innerText()!=='0','save persists');assert.equal(await p.locator('.reward-float,#toast').count(),0);assert.equal(await p.locator('.feedback-strip').count(),1,'bounded feedback node');await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.sun-motes').evaluate(e=>getComputedStyle(e).display),'none');await p.emulateMedia({reducedMotion:'no-preference'});if(profile.name==='mobile-390'){await p.setViewportSize({width:844,height:390});await shot(p,'mobile-landscape-home');assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await p.locator('.room-bottom .main-cta').evaluate(e=>{const r=e.getBoundingClientRect();return r.bottom<=innerHeight&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===e;}));await activate('.room-bottom .main-cta');await p.getByRole('dialog',{name:'创作者工作台'}).waitFor();assert(await p.locator('.sheet-footer').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight));assert(await p.locator('.sheet-content').evaluate(e=>e.getBoundingClientRect().height>=130),'landscape options have readable content space');assert(await p.locator('.select-card').first().evaluate(e=>{const r=e.getBoundingClientRect(),c=e.closest('.sheet-content').getBoundingClientRect();return r.top>=c.top&&r.bottom<=c.bottom&&r.height>=75&&document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===e;}),'whole landscape option visible and hit-testable');await shot(p,'mobile-landscape-create');await p.keyboard.press('Escape');await p.setViewportSize({width:390,height:844});}
 const frames=await p.evaluate(()=>new Promise(resolve=>{const v=[];let last;function f(t){if(last!==undefined)v.push(t-last);last=t;if(v.length<180)requestAnimationFrame(f);else resolve(v.sort((a,b)=>a-b));}requestAnimationFrame(f);}));const p95=frames[Math.floor(frames.length*.95)];console.log(JSON.stringify({profile:profile.name,p95}));assert(p95<=35,'browser frame budget: '+p95);
 report.profiles.push({name:profile.name,status:'passed',firstVideoViews:views,realInput:true,secondVideo:true,roomPurchase:true,saveRestore:true,p95,geometry,hero,bundledBrushFont:true,paintedEntrances:true,editingArtClear:true,realPoolResult:true,dialogFocus:true,accurateUpgradePreview:true,boundedFeedback:true,reducedMotion:true,errors});report.errors.push(...errors);
 await ctx.close();
}
// State fixtures below are visual-only, separate from genuine playthrough above.
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});const p=await ctx.newPage();await p.goto(url);
// Complete a genuine first video, then copy its save into isolated visual-only contexts.
await p.locator('.main-cta').click();await p.locator('.main-cta[data-action="publish"]').waitFor({timeout:10000});await p.locator('.main-cta[data-action="publish"]').click();await p.locator('[data-action="publishWith"][data-id="reply"]').click();await p.getByRole('dialog',{name:'本条作品成绩出炉！'}).waitFor({timeout:10000});await p.locator('[data-action="closeLive"]').click();await p.reload();
const visualState=await p.evaluate(key=>JSON.parse(localStorage.getItem(key)),KEY);await ctx.close();
for(let tier=0;tier<4;tier++){
 const visual=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
 const fixture={...visualState,roomTier:tier,day:26,level:4,fans:404,views:27500,wallet:185,guideStep:4,pendingEvent:null,lastSavedAt:Date.now()};
 await visual.addInitScript(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key:KEY,state:fixture});
 const page=await visual.newPage();await page.goto(url);await page.locator('.room-illustration').evaluate(img=>img.decode());await page.evaluate(()=>document.fonts.load('24px CreatorBrush'));await page.locator('.illustrated-actions img,.work-thumbnail').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));
 assert.equal(await page.locator('.room-illustration').getAttribute('src'),'./assets/'+['room-rental-v05.webp','room-cozy-v05.webp','room-pro-v05.webp','room-star-v05.webp'][tier]);
 assert.equal(await page.locator('#fan-counter').innerText(),'404');await shot(page,'visual-room-tier-'+tier);
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.sun-motes').evaluate(e=>getComputedStyle(e).display),'none');await visual.close();
}
const target=await b.newContext({viewport:{width:512,height:768},deviceScaleFactor:2});
await target.addInitScript(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key:KEY,state:{...visualState,roomTier:1,day:3,level:2,wallet:185,guideStep:4,pendingEvent:null,lastSavedAt:Date.now()}});
const targetPage=await target.newPage();await targetPage.goto(url);await targetPage.evaluate(()=>document.fonts.load('24px CreatorBrush'));await targetPage.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(img=>img.decode())));await shot(targetPage,'target-composition-512');assert(await targetPage.locator('.mission-card').evaluate(e=>e.getBoundingClientRect().bottom)<=await targetPage.locator('.room-bottom .main-cta').evaluate(e=>e.getBoundingClientRect().top-10),'target composition keeps latest work above CTA');await target.close();
assert.equal(report.errors.length,0,JSON.stringify(report.errors));report.status='passed';
}catch(e){report.status='failed';report.failure=String(e);process.exitCode=1;}finally{await b.close();report.screenshots=shots;writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({status:report.status,failure:report.failure,profiles:report.profiles.map(p=>({name:p.name,p95:p.p95})),screenshots:shots.length,errors:report.errors}));}
